### ISSUE TITLE
Show correct visualisation on data source selection page

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#109]
### Description
Right now it tells you which visualisation it should display. You can likely copy a lot of the logic from visualisation editor page.

### Subtasks
- [x] Display correct visualisation

**Comment by Kpaubert** [comment]
Fixed this for when you run in production, just a couple of questions:
* Should this work when in dev (mock-data gives out wrong visualisation types)? 
* This is only tested for line graphs, how can I test easily with threshold/other?

@FredrikAugust <3

**Comment by Kpaubert** [comment]
Both points solved, all that needs doing is changing MockMetadata.cs in the backend like this:
![image](https://user-images.githubusercontent.com/43110067/113914261-a95dde80-97dd-11eb-946c-03a82c03bab7.png)
Can probably be done as a separate issue in the backend.

Also wondering, ref. the image: should the threshold return an array?

**Comment by FredrikAugust** [comment]
1) My branches in PR resolve this
2) Move the threshold recommended visualisation type for MetAPI to the top

**Comment by FredrikAugust** [comment]
> Both points solved, all that needs doing is changing MockMetadata.cs in the backend like this:
> ![image](https://user-images.githubusercontent.com/43110067/113914261-a95dde80-97dd-11eb-946c-03a82c03bab7.png)
> Can probably be done as a separate issue in the backend.
> 
> Also wondering, ref. the image: should the threshold return an array?

That's already live in effect

https://github.com/IT2901-SINTEF01/backend/blob/19f91e8331d8ba388fe38605c753e8d356b17d4a/Mocks/Metadata/MockMetadata.cs#L30

And no, threshold should be a single integer AFAIK.

**Comment by Kpaubert** [comment]
Ah, perfect. Moving my PR from draft to ready for review in that case 👍
