### ISSUE TITLE
Replace custom visualisations with graphs from decided backup graph library

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#120]
### Description
As discussed in the meeting, we should use the pre-made charts instead as they are _better_.

### Subtasks
- [x] Find out which library it is
- [x] Replace LineChart
- [x] Replace ThresholdChart (if possible)

**Comment by emilom** [comment]
Maybe this will help

https://github.com/IT2901-SINTEF01/frontend/issues/4
https://github.com/IT2901-SINTEF01/frontend/wiki/Visualisation-tools

**Comment by FredrikAugust** [comment]
I would also like to plug [Plot.ly for React](https://github.com/plotly/react-plotly.js). They feature exporting to PNG which would automatically resolve one of our milestones.

It's also a very commonly used library which should suffice all our graphing needs.

**Comment by Kpaubert** [comment]
I'll try with Plot.ly first. Commenting here with update after some testing.

**Comment by Kpaubert** [comment]
## Plot.ly update:
![image](https://user-images.githubusercontent.com/43110067/114178316-dcb77f00-993d-11eb-8c37-6d43bb4f1c67.png)
###  Pros
* It was very easy to implement, configure and make it work with the existing data. All that was required was to include the library, and use a `<Plot ...{configuration} />`-tag.
* Has a lot of user-options (omitted in the image above, as there is no reason to export mocked data). The user can interact with the graph in various ways.
### Cons
* Probably does require some more configuration to look as good as visx. Mainly because of an artificial padding on the graph, not filling the screen.

<details>
<summary>Code example</summary>

<p>

```tsx

<Plot
    data={[
        {
            x: timeEntryMockData.map((entry) => entry.x),
            y: timeEntryMockData.map((entry) => entry.y),
            type: 'scatter',
            mode: 'lines',
            line: { shape: 'spline' },
            marker: { color: 'red' },
        },
    ]}
    style={{ width: '100%', height: '100%' }}
    layout={{
        autosize: true,
        title: `Forslag til visualisering for ${title}: ${friendlyNameForVisualisationType(
            visualisationType,
        )}`,
    }}
    config={{ staticPlot: true }}
/>
```

</p>
</details>

Testing out rechart next.

**Comment by Kpaubert** [comment]
## Recharts update
![image](https://user-images.githubusercontent.com/43110067/114183451-feb40000-9943-11eb-96cf-59674d335c6e.png)
### Pros
* Can look reaally nice
* Lots of configurability
* Not too hard to implement correct data structures
### Cons
* Awkward syntax compared to visx and recharts (personal opinion)
* A bit harder to configure correctly

<details>
<summary>Code example</summary>

<p>

```tsx

<AreaChart data={data} width={950} height={288}>
    <defs>
        <linearGradient id="colorUv" x1="0" y1="0" x2="0" y2="1">
            <stop offset="5%" stopColor="#8884d8" stopOpacity={0.8} />
            <stop offset="95%" stopColor="#8884d8" stopOpacity={0} />
        </linearGradient>
        <linearGradient id="colorPv" x1="0" y1="0" x2="0" y2="1">
            <stop offset="5%" stopColor="#82ca9d" stopOpacity={0.8} />
            <stop offset="95%" stopColor="#82ca9d" stopOpacity={0} />
        </linearGradient>
    </defs>
    <XAxis dataKey="name" tickCount={5} interval={18} />
    <YAxis />
    <CartesianGrid strokeDasharray="3 3" />
    <Tooltip />
    <Area type="monotone" dataKey="value" stroke="#8884d8" fillOpacity={1} fill="url(#colorUv)" />
    <Area type="monotone" dataKey="pv" stroke="#82ca9d" fillOpacity={1} fill="url(#colorPv)" />
</AreaChart>
```

</p>
</details>

Any thoughts? @IT2901-SINTEF01/frontend

**Comment by blauks** [comment]
I like the looks of Recharts a lot more than plot.ly. So I would go of that.

**Comment by FredrikAugust** [comment]
Personally I'd vouch for plot.ly due to the amount of features we get for free using that[0]. Recharts is quite visually appealing, but doesn't sport any "extra" features.

Considering we're very strapped on time, I would like to emphasise the fact that Plot.ly was easier to work with, and features a lot of extra features.

We're already in the situation we're in now because we decided to use visx for charts there existed solutions for already. Recharts seems like it might land us in the same trap, as it's a lot lower level than Plot.ly. Take a look at an example from Recharts and notice how similar to visx it looks: https://recharts.org/en-US/examples.

Plot.ly is an "all batteries included" chart library, whereas Recharts is a lower level library of composable chart "parts".

While good looks is a nicety, I think we should focus on what provides results fastest.

[0] You can export the graph, zoom, pan, &c

**Comment by emilom** [comment]
I agree with @FredrikAugust.  Functionality is more important than looks now

**Comment by FredrikAugust** [comment]
**CONCLUSION**
- Use plot.ly for functionality
