### ISSUE TITLE
Update wiki with atomic design spec

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#125]
### Description
We now use the entire [atomic design](https://bradfrost.com/blog/post/atomic-web-design/) specification.

Update wiki accordingly.

### Related sources
- https://bradfrost.com/blog/post/atomic-web-design/

**Comment by blauks** [comment]
😀

**Comment by blauks** [comment]
In our case, are templates and pages the same thing?

**Comment by FredrikAugust** [comment]
No, templates wrap pages and provide a common baseline.

They're often called "Layout" IIRC

**Comment by FredrikAugust** [comment]
It's basically

```
Layout(Page)
  - Organism(s)
    - Molecule(s)
      - Atom(s)
```

**Comment by FredrikAugust** [comment]
If that makes any sense. I.e. `<Layout><Page /></Layout>` will provide some structure around the page to reduce redundancy.

**Comment by blauks** [comment]
Ah okay, I think I understand.

**Comment by blauks** [comment]
Now it should be ~ok.
