### ISSUE TITLE
Discuss utility vs presentational value

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#14]
A question mainly for @IT2901-SINTEF01/ux-design, but including @IT2901-SINTEF01/frontend as this will determine their choice of technologies.

When developing dashboards and visualisations it's important to strike a good balance between utility and :sparkles: _aesthetics_ :sparkles:. 

We should probably set some guidelines for the visualisation of data with regards to amount of information, design &c. 

Example questions:
- Can we use smoothing on line charts? This doesn't provide the same amount of granular detail, but looks better
- Do we want to focus on creating beautiful visualisations that can be used in e.g. marketing or on websites and convey exciting information, or very "statistical" visualisations that target data scientists and researchers? Can we do both?
- Do we want to spend time implementing animations? They are a huge improvement to the visual impression of the website and give the user a feeling of an interactive experience.
- Do we want to create a theme between all the components? E.g. use of gradients and rounded corners?

--------

It's a fine line, but I believe it should be at least given some discussion.

- [x] Include in meeting notes for Wednesday

**Comment by FredrikAugust** [comment]
The conclusion of this debate should probably be reflected in the report as well as mentioned on the wiki under a "Design Philosophy" section.

**Comment by thomran** [comment]
How about discussing this in detail when we meet on wednesday? I agree that this is a subject where we should be in agreement from the go, and I think some aspects of this discussion should be held with the entire team.

**Comment by FredrikAugust** [comment]
Sounds good. I suppose we can include this in the user story creation.

**Comment by FredrikAugust** [comment]
Discussed [here](https://hackmd.io/Z9drv5AuQ4i00VyUfJXREA?view#10-min-Utility-vs-design).

Closing.

**Comment by FredrikAugust** [comment]
Conclusion:

> Choose one backup-library and one "low level" visualisation framework.
> Attempt to create custom components, with fallback.
