### ISSUE TITLE
Update package docs to reflect variables

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#147]
### Description
Post #146 the components in the package require variables that will be passed into the graphql request. This should be reflected in the documentation. Should be self-explanatory, but let me know if you have any questions or problems!:)

**Comment by blauks** [comment]
Should I publish the new updates aswell?

**Comment by FredrikAugust** [comment]
Would be great!

**Comment by blauks** [comment]
[Updated](https://github.com/IT2901-SINTEF01/frontend/wiki/%22data-visualisation-platform%22) :):):)
