### ISSUE TITLE
Add bar chart visualisation

### ISSUE THREAD

**Issue by emilom** [IT2901-SINTEF01/frontend#154]
We should add a bar chart to support the new dataset and make the application more spicy 🥵 🌶 
Will be using standard bar charts and grouped bar charts  from plotly without much customisations.

Tasks
- [x] Support the current data sources.
- [ ] Support new data set from https://github.com/IT2901-SINTEF01/backend/issues/139
- [ ] Add storybook

**Comment by FredrikAugust** [comment]
Could you update this issue to contain the relevant information?

I.e. what needs to be done, and perhaps what (if any) data sources it should support.

There is a template there for a reason.

**Comment by FredrikAugust** [comment]
- What parts of the application need to be updated?
- Should it be a complete implementation of a visualisation such that a new data source only needs to add support for it, or only the chart?
- Storybook?
- Barcharts come in many shapes and sizes, which one should be used? Only the standard or should we allow for customisation? [Ref. plot.ly docs](https://plotly.com/python/bar-charts/)
