### ISSUE TITLE
LatLon input with default vars is detected as modified

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#158]
### Description
Going to edit page for LatLon-input vis. with default variables is detected as modified dashboard visualisation.

### Steps to reproduce
1. Add new visualisation with lat+lon input
2. Click "edit" on dashboard (pencil icon)
3. Look at the "Update visualisation button"

### Expected behaviour

Should not be detected as modified as the default variables are the same as the "default variables".

### Additional comments

Not a critical error. Clicking "update" doesn't actually change anything, and works if you use something else than the default variables.

**Comment by FredrikAugust** [comment]
@blauks any updates on this?

**Comment by blauks** [comment]
It's coming together really well now, I just have some small adjustments to make it perfect. __Also__ do you want it to feel like this 
![bilde](https://user-images.githubusercontent.com/33070123/124757767-37a54600-df2e-11eb-96a7-7236d3155649.png)
or more like this 
![bilde](https://user-images.githubusercontent.com/33070123/124757844-4c81d980-df2e-11eb-8a83-dbaa124fc322.png)
?

Thanks for your input!

**Comment by FredrikAugust** [comment]
@blauks I don't think I'm qualified to answer this question. What do you think, designer @thomran?

Perhaps @Kpaubert knows more about the implementation details?

**Comment by FredrikAugust** [comment]
But I'm leaning towards the tower.

**Comment by thomran** [comment]
@FredrikAugust I see what you did there. I too lean towards the tower! Designer approved, even though the UX might be a bit overly lean.

**Comment by FredrikAugust** [comment]
@thomran I'll admit _I fell_ for the first one initially, but as you say; lean development is important.

**Comment by Kpaubert** [comment]
Now this, is epic.
