### ISSUE TITLE
Document use of Storybooks

### ISSUE THREAD

**Issue by blauks** [IT2901-SINTEF01/frontend#18]
Document how to set up and use Storybooks.

Helpful notes from @FredrikAugust 

> Useful points:
> 
> - File name format. With this configuration, they have to be (in effect) *.stories.tsx
> - How does a story look? Perhaps provide an example
> - Should you be able to test container components, or only presenational? If you should be able to test container components, it might be useful to provide a wrapper.

**Comment by blauks** [comment]
Will be done after I have finished #1

**Comment by FredrikAugust** [comment]
What's the status on this?

**Comment by emilom** [comment]
Im testing some visx now. Will try to set it up with storybooks when I'm done and document it. Probably done by tomorrow afternoon.

**Comment by FredrikAugust** [comment]
Perfect!:)

**Comment by blauks** [comment]
[Storybook wiki](https://github.com/IT2901-SINTEF01/frontend/wiki/Storybook) @emilom has fixed 🥳
