### ISSUE TITLE
Create type and dummy data which corresponds to MetAPI response

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#27]
### Description
Create a type which corresponds to the response of the MetAPI call. Hopefully, soon you will be able to use the backend to retrieve this data, but this is currently under review.

This type will be the type of the deserialised result from the GraphQL query. If you have any questions about how this works, @blauks should have some knowledge from Ekskom!;)

The dummy data you create could be a JSON file you put in a sensible location, or a JS object in a file. You only have to make sure it's an exact match between the type and the data.

### Subtasks
- [x] Create folder in a logical place for collecting different types
- [x] Create type
- [x] Create sample data which is of the newly created type (e.g. `const sample: MetApiCompactForecast = { ... };`)

### Related sources
- Data source: https://api.met.no/weatherapi/locationforecast/2.0/#!/data/get_compact
- _[might be useful](http://json2ts.com)_

**Comment by emilom** [comment]
Am I supposed to create a folder with a file containing all the different types/interfaces for the data we will be using?

**Comment by blauks** [comment]
I like the idea of having a folder for all our types and interfaces!

**Comment by FredrikAugust** [comment]
> Am I supposed to create a folder with a file containing all the different types/interfaces for the data we will be using?

Yep! Perhaps a folder with folders?

- `DataTypes`
  - `MetApi`
    - `Compact`

Etc. Would be helpful if we e.g. get multiple data sources from data.norge.no.

**Comment by emilom** [comment]
sounds good 👌
