### ISSUE TITLE
Create palette based on design in Evergreen

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#28]
### Description
This should be done once the design is at least partially complete – to the point where colours have been set in stone.

### Subtasks
- [x] Update Evergreen config to use your new custom colours.
- [x] Make a decision whether or not you want to support dark mode (confer: @IT2901-SINTEF01/ux-design) and write a sentence about it in Wiki->Design

### Related sources
- https://evergreen.segment.com/get-started/theming

**Comment by emilom** [comment]
Good job!
