### ISSUE TITLE
Design user interface ✨ 

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#31]
### Description
Afternoon, @IT2901-SINTEF01/ux-design. 
The task is to create a _more complete_ design in Figma that the @IT2901-SINTEF01/frontend team can use as a baseline for their implementation.

### Subtasks
- [x] Create design
- [x] Add design to design page in wiki

**Comment by thomran** [comment]
The first iteration of the user interface will be finished before tomorrow, (25.02.2021).

**Comment by thomran** [comment]
The design process took longer than expected and is therefore not yet finished. The first iteration of the user interface design is now estimated to be completed before friday (27.02.2021).

**Comment by FredrikAugust** [comment]
:ok: sounds good!

**Comment by thomran** [comment]
The user interface design is now completed and added to the design page in the wiki. 

The actions of each button press, as well as all empty states and edge cases have not yet been thoroughly completed, but will be viewed in detail and completed as soon as possible. Said subtasks are estimated to be taken care of tomorrow, (26.02.2021)
