### ISSUE TITLE
Design for loading and error

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#32]
### Description
The datasets might take some time to load, and may even produce errors. We should have visual components representing these outcomes.

### Subtasks
- [x] Create loading and error designs for datasets, visualisations and other elements which require loading of external resources

**Comment by FredrikAugust** [comment]
@thomran any updates on this?

**Comment by thomran** [comment]
Should be completed later today! (02.03.2021)

**Comment by FredrikAugust** [comment]
Superb!

**Comment by FredrikAugust** [comment]
@thomran could you also create a component for when no data is retrieved from the backend?

**Comment by FredrikAugust** [comment]
I.e. missing data.

**Comment by thomran** [comment]
On it!

**Comment by FredrikAugust** [comment]
Perfect!

**Comment by thomran** [comment]
Done! Will fill out wiki with new content tomorrow. 

Will also need to discuss some aspects of the design in tomorrow's meeting.
