### ISSUE TITLE
Add proxy configuration to avoid CORS restrictions

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#34]
I got it to work with using proxies on frontend. 

Steps to reproduce: 
- Add to package.json:
```json
    "proxy": "http://localhost:5000",
```
- Code used for testing
```tsx
            <button
                onClick={() =>
                    fetch('/graphql', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: `{"operationName":null,"variables":{},"query":"{ forecast { forecastGeometry { coordinates } } } "}`,
                    })
                }
            >
                test
            </button>
```

Remember that when proxying you need to make a request to the host you're serving the app from. This is done by default when omitting the host in the `fetch` request, and only including the path.

_Originally posted by @FredrikAugust in https://github.com/IT2901-SINTEF01/backend/issues/29#issuecomment-781462533_

**Comment by blauks** [comment]
Nice, thanks for the help!:)
