### ISSUE TITLE
Containerise application

### ISSUE THREAD

**Issue by blauks** [IT2901-SINTEF01/frontend#5]
Build the application in a docker image and publish to organisation – just like backend.
An umbrella repo will be created which deploys both of these (with a DB in the future) with a docker-compose "image".

**Comment by FredrikAugust** [comment]
Adding wontfix for now. Remove when applicable.

**Comment by blauks** [comment]
Sounds good Mr. Laos!

**Comment by FredrikAugust** [comment]
See you on Bali, boys!

**Comment by FredrikAugust** [comment]
@blauks 
Did you hear about the seagull who was tasked with containerising the frontend app?
_He winged it._

**Comment by blauks** [comment]
Funny! 🙂
