### ISSUE TITLE
Set up a mocked provider for use in storybook

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#51]
### Description
To provide some more interesting data to the components in the storybook (as well as avoiding having to store large JSON files everywhere) we can use a mocked provider from apollo.

### Subtasks
- [x] Set up a [decorator](https://storybook.js.org/docs/react/writing-stories/decorators) which provides the mocked provider
- [x] Mock the api.met.no request

**Comment by blauks** [comment]
This is done under the #49 PR.

**Comment by FredrikAugust** [comment]
Add "Closes #51" to the description of the PR. 

The issue is not "done" before it's merged into `master`.
