### ISSUE TITLE
Global store for keeping track of selected visualisations

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#55]
### Description
The frontend needs to keep track of which visualisations are selected, and a global store is a suitable place for that. I believe @emilom found the Apollo state management to be sufficient, so that should be used.

### Subtasks
- [x] Create store and model
- [ ] **Test** (Unit test) selecting a data source and make sure it's reflected in the store. Do not need UI test

**Comment by blauks** [comment]
@emilom has already correctly implemented the Apollo state management, but I will implement a little test 😃

**Comment by FredrikAugust** [comment]
Perfect, @blauks.

**Comment by blauks** [comment]
Thanks @FredrikAugust
