### ISSUE TITLE
Make this project into a library

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#64]
### Description

This project should be usable as a npm library.

### Subtasks
- [x] Find out how to use this project as a library
- [x] Create example repository using this library under IT2901-SINTEF01

**Comment by FredrikAugust** [comment]
What is the status on this, @blauks?

**Comment by FredrikAugust** [comment]
I've updated the milestone to have a deadline 23. April, as it's crucial we get this resolved as soon as possible.

**Comment by blauks** [comment]
Hello @FredrikAugust, thanks for checking in. I have not been able to work on this as much as I wanted to, but I will work on it this week. I think I should be able to finish this, or atleast have a very good plan on how we should do it, within the end of the week.

**Comment by blauks** [comment]
Ok so basically, my current plan is: 
1. Create a new folder (called npm, or whatever), where I create the components that I want to export as the NPM package.
    - For example, a datawrapper wrapped around a dashboard item. 
2. Then create props for the new components, that would let a user choose everything that is needed for displaying a visualisation (Title, source, text... etc.), without needing the state manager that we use in our dashboard.
3. Configure package.json with all the necessary metadata (description, name, author, contributers, peer dependencies)
4. Use rollup to compile the project to Javascript
5. Publish on NPM 

That is basically it, hope it makes sense. It was not as complicated as I had first thought. The main thing to get out of this is the first part I suppose. I basically create a new component that is only used for the NPM package, as the methods we have used to display visualisations now would not really work on other websites.

**Comment by FredrikAugust** [comment]
Could you provide an example of what these components would look like? Preferably with some example code?

**Comment by blauks** [comment]
```typescript
const DataVisualiserObject: React.FC = ({}) => {
    return (
        <DashboardItem title={'test'} height="100%" width="100%" titleSize={100} paragraph={'test'}>
            <ParentSize>
                {(parent) => (
                    <DataWrapper
                        mappingFunction={dataSourceMappings['MetAPI Forecast'].mapping}
                        query={dataSourceMappings['MetAPI Forecast'].query}
                    >
                        {(data) => <ThresholdChart data={data} height={parent.height} width={parent.width} />}
                    </DataWrapper>
                )}
            </ParentSize>
        </DashboardItem>
    );
};
```

They wouldn't be so complicated, something _ish_ like this. This would also be wrapped in an Apollo Provider. And I need to find the best way for how one can choose the graph, either they can pass in a child or we can just use enums.

**Comment by FredrikAugust** [comment]
I see. Would it be possible to export an object like this?

```tsx
export const MetApi = {
  Line: <LineChart data={...} />
}
```

so you could use it like

```tsx
<MetApi.Line />
// and
<SsbPopulation.Threshold />
```

Does the user need to know anything else? This way you could spare them from having to deal with queries and mappings themselves. Ideally they should need to understand as little as possible to embed their components

**Comment by FredrikAugust** [comment]
Naturally they would require some way of controlling styling, but I believe that's it?

**Comment by blauks** [comment]
That seems like a good solution! My focus is to make it as easy as possible to use. I will try to make something usable today, and provide a better example :)
