### ISSUE TITLE
Correct GQL Query should be used on dashboard

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#71]
### Description

Right now, the query used on the dashboard is not correct, and this needs to change.

We are gathering an army and preparing to tackle this enormous hindrance.

Sharpen your tools, we're going into war.

### Subtasks
- [x] Create function for determining which type and query should be used based on selections on data chooser pages

**Comment by FredrikAugust** [comment]
Hello, @emilom 

I am Fredrik, but you might know me as :fredriksinna:. I'll get started on this issue now, let me know if you wish to join in on Zoom or something along those lines.

**Comment by emilom** [comment]
I'm down for some zooming

**Comment by FredrikAugust** [comment]
Done-diddely-doo

![](https://pbs.twimg.com/profile_images/378800000395351168/75ace8ef8d8c184ac3136f80a4d340cc_400x400.jpeg)
