### ISSUE TITLE
Update design of visusalisation editor page

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#73]
### Description
It doesn't look good.

😷 

### Subtasks
- [x] "Trenger bare litt padding"

**Comment by FredrikAugust** [comment]
@emilom can this issue be closed by #77?

**Comment by FredrikAugust** [comment]
I suppose _cloeses_ means that it should be closed.

**Comment by emilom** [comment]
my bad, little typo

**Comment by FredrikAugust** [comment]
🛩️
