### ISSUE TITLE
Storybook invalidates each run due to diff in text in stories

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#75]
### Description
Storybook invalidates all components as they differ in textual content.

PLEASE 🙏🏻 

It also makes all builds in master pending as they're not accepted.

### Steps to reproduce
1. Push new build to git repo

### Expected behaviour
No diff.

**Comment by FredrikAugust** [comment]
Could probably be smart to make the mocked data always return the same in stories.

**Comment by blauks** [comment]
Okey dokey
