### ISSUE TITLE
Create new visualisation component for populationsInNorway data set

### ISSUE THREAD

**Issue by emilom** [IT2901-SINTEF01/frontend#79]
### Description
A threshold chart will not be the best way to visualise population data in Norway. We should create a new component for line charts which can be added to our library of available visualisation methods.

### Subtasks
- [ ] Create a line chart in visx

**Comment by blauks** [comment]
Good insj

**Comment by FredrikAugust** [comment]
Does the SSB population dataset include historical data?

**Comment by emilom** [comment]
Yes :)
