### ISSUE TITLE
Display visualisation selected by user (and not always thresholdchart) 📊 

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#82]
### Description
Make chart type dependent on vis. selected -- i.e. information available in global store after #85.

#### Conciderations

It might be easier to have all visualisations accept an object (i.e. _one_ argument) and use some clever mapping between input and output.

### Subtasks
- [ ] Decide what type of visualisation should be shown
- [ ] Map from raw data to visualisation input

**Comment by blauks** [comment]
Always thresholdchart 😡

**Comment by Kpaubert** [comment]
Thoughts on this, @fredrikbw?

**Comment by FredrikAugust** [comment]
Thoughts, please
