### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by thomran** [IT2901-SINTEF01/frontend#89]
A review of the application accessibility can be found [here](https://www.notion.so/Accessibility-review-f199dd0e4aec4a0f9a4f227b97cadf8c). The review provides an overview of tasks to be done and explains the tasks below in greater detail.

- [x] Make all custom controls into native HTML elements. If this is not possible, they should have associated labels and ARIA roles.
- [x] Add labels and/or text alternatives where necessary.
- [x] Give focus to pop-up alerts when they appear.

**Comment by FredrikAugust** [comment]
Great work!

**Comment by FredrikAugust** [comment]
I propose that one of you in @IT2901-SINTEF01/frontend take responsibility for this issue to ensure that it is done.

Who would like to do the honors?

**Comment by FredrikAugust** [comment]
If you would like to take this issue, unassign the erst.

**Comment by blauks** [comment]
@emilom this is the mission you were made for, good luck out there. Rooting for you

**Comment by emilom** [comment]
@blauks thanks 🙏

**Comment by blauks** [comment]
@emilom 😘
