### ISSUE TITLE
Design updates Vercel

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/frontend#98]
### Description
Some thoughts regarding the current Vercel design.

Would also like some input from @IT2901-SINTEF01/ux-design.

- The footer is placed beneath the screen even though there's space for it
- The Vercel logo is centered, which seems slightly inconsistent with the rest of the design
- The Vercel logo is very large. Can it be scaled down?

**Comment by blauks** [comment]
I see your concern, the implementation was a little bit rushed. I do not really know why it is placed beneath the screen when there is space for it, but I am going to try and fix it now. About the centration, I guess it would make more sense to move it to the left of the screen? But design is not really my cup of tea. 
We could probably make the logo a little bit smaller. 

I also found out that the footer looks very weird in the visualisation editor view. I will fix it:)

**Comment by FredrikAugust** [comment]
Deprecate in favour of #101?

Would it also be possible to simply revert the Vercel design-updates?

**Comment by FredrikAugust** [comment]
Also, a strange visual bug appears on the deployed site

<img width="1904" alt="Screenshot 2021-04-05 at 18 28 43" src="https://user-images.githubusercontent.com/7691547/113598683-cbb8f600-963d-11eb-8e6a-9557898099a1.png">

**Comment by blauks** [comment]
Bye bye issue

**Comment by emilom** [comment]
bye

**Comment by FredrikAugust** [comment]
bye gyus
